### PR TITLE
Create build process

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
New Build started 🖕

**Comment by wtrocki** [comment]
@ani-sha Note. I did not added tests to CI yet as we do not have any. We will add those later stage.

**Comment by wtrocki** [comment]
Screenshot 2020-06-24 at 16 10 14

Good Job @ani-sha ! All goes here. We do not require reviews for trivial changes so feel free to merge those small things, but for code changes it is better to as for reviews.

**Comment by ani-sha** [comment]
> New Build started 🤞



> @ani-sha Note. I did not added tests to CI yet as we do not have any. We will add those later stage.

yes will do that.

**Comment by ani-sha** [comment]
> Screenshot 2020-06-24 at 16 10 14
> 
> Good Job @ani-sha ! All goes here. We do not require reviews for trivial changes so feel free to merge those small things, but for code changes it is better to as for reviews.

Sure thing. Thanks.

**Pull request merged**
